architecture: replication
metadata:
  namespace: exercise
auth:
  existingSecret: mysql-chart-secret
  database: my-db
  username: tanner
volumePermissions:
  enabled: true
secondary:
  replicaCount: 2
  persistence:
    accessModes: ["ReadWriteOnce"]
    storageClass: "linode-block-storage"


