architecture: replication
metadata:
  namespace: exercise
auth:
  existingSecret: mysql-secret
volumePermissions:
  enabled: true
secondary:
  replicaCount: 2
  persistence:
    accessModes: "ReadWriteOnce"
    storageClass: "linode-block-storage"


