architecture: replication
auth:
  existingSecret: mysql-chart-secret
  database: my-db
  username: tanner
  replicationUser: replicator
volumePermissions:
  enabled: true
secondary:
  replicaCount: 2
  persistence:
    accessModes: ["ReadWriteOnce"]
    storageClass: "linode-block-storage"
  startupProbe:
    enabled: false


