apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.2.0-fpm-alpine
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: db_root_pwd
          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: db_server
          - name: PMA_PORT
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: pma_port
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
